#!/bin/sh

set -e
set -u

WWW_DIR="${1:-}"
CURRENT_YEAR="$(date +"%Y")"
YEAR="${2:-}"

if [ -z "$WWW_DIR" ]; then
	>&2 echo "ERROR: Please set destination directory"
	exit 1
fi

if [ -z "$YEAR" ]; then
	>&2 echo "ERROR: Please set year (number|all|current)"
	exit 1
fi

case "$YEAR" in
	current)
		YEAR_START="$CURRENT_YEAR"
		YEAR_END="$CURRENT_YEAR"
		;;
	all)
		YEAR_START="2016"
		YEAR_END="$CURRENT_YEAR"
		;;
	*)
		YEAR_START="$YEAR"
		YEAR_END="$YEAR"
		;;
esac

for year in $(seq "$YEAR_START" "$YEAR_END"); do 
	fi-cli fetch -o - "$year" \
		| fi-cli convert -o "$WWW_DIR/$year.json" -
done


